name: Periodic Health Check

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-5nlq.onrender.com

      - name: Notify success
        if: success()
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: info
          details: Health check passed!
      - name: Notify failed
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          severity: error
          details: Health check failed
    
