name: Periodic Health Check

on:
  push:
    branches:
      - main

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-5nlq.onrender.com
    
